name: Generate Keystore

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Crear keystore
        run: |
          keytool -genkeypair \
            -alias mykey \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -keystore keystore.jks \
            -storepass 123456 \
            -keypass 123456 \
            -dname "CN=App, OU=Dev, O=MyApp, L=City, S=State, C=US"

      - name: Convertir a base64
        run: base64 keystore.jks > keystore.txt

      - name: Subir archivo
        uses: actions/upload-artifact@v4
        with:
          name: keystore
          path: keystore.txt
