name: Build APK (Flet Android 15)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      CI: "true"
      FLET_FORCE_AUTO_INSTALL: "true"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Flet
        run: |
          pip install --upgrade pip
          pip install flet

      - name: Build APK
        run: yes | flet build apk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: bola-caliente-apk
          path: build/app/outputs/flutter-apk/*.apk
